### ISSUE TITLE
Paragraph style cloze 

### ISSUE THREAD

**Issue by mullerrwd** [Pseudonium/Obsidian_to_Anki#106]
Hi @Pseudonium,

FYI, I'm afraid the new [cloze regex](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Cloze-Paragraph-style
) will only capture single lines. Not paragraphs. This would capture whole paragraph:
```
((?:.+\n)*.*{(?:[^\n][\n]?)+)
```
Through it will capture other unwanted items.

Related to my comment in #81, I eventually came up with the following regex:
```
((?:.+\n)*.*\s(?=\{\s+|\{.\d+\:|\{\d+\:)(?:[^\n][\n]?)+)
```
- Capture whole paragraph for either of below specific cases (look ahead). Curly bracket followed by:
 - a whitespace
 - any character, followed by any number of digits and a colon
 - any number of digits and a colon.

Demo: https://regex101.com/r/xJS1Nj/1

This will correctly capture paragraphs, ignore math mode and ignore template definitions enclosed within double curly brackets.
I now prefer a space after and before the curly brackets as this helps with readability . E.g. { some cloze } vs {some cloze}

However, I am not a seasoned regex expert. So a sanity check would be more than welcome.

**Comment by Pseudonium** [comment]
So, first of all, we no longer have to worry about accidentally matching a { inside a math expression or a code expression if the script does identify a card as a cloze, but doesn't find any actual cloze deletions (because of the { actually being inside a math or code expression), it just won't add the card!

**Comment by Pseudonium** [comment]
And yes, I did realise that I changed it to be only single lines rather than paragraphs (though in an editor often a paragraph is really a single line). Reason being I was having some issues with 'double ID' occurring - I'll see if that issue is still occurring. If it is I might just keep it as a single line (I think the examples given still work?), and if it's not I'll put up a "paragraph" regex.

**Comment by Pseudonium** [comment]
Ok, I've changed the wiki section to have a paragraph regex, let me know if there are any problems

**Comment by mullerrwd** [comment]
Seems to work perfectly! Thanks for the adjustment @Pseudonium
