### ISSUE TITLE
Automatic uninstall of plugin

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#157]
Possibly due to running Obsidian without ANKI opened led to uninstall of the whole plugin! Not even disable, but it got uninstalled :/

![image](https://user-images.githubusercontent.com/68785729/102132406-9b283300-3e79-11eb-9cc0-7e98be7c3a9a.png)

EDIT: The settings were preserved. 💯

**Comment by Pseudonium** [comment]
No idea what could've caused this, I've run Obsidian multiple times with the plugin installed and Anki open and this never happened. It can't have been a complete uninstall either if settings were preserved, since a complete uninstall would remove the actual plugin folder, which is where settings are installed.

Probably worth trying to raise this with the Obsidian devs themselves as a bug report, if you can reproduce this.

**Comment by dummifiedme** [comment]
If it reproduces, will try to raise it with the Obsidian team. Sure.
