### ISSUE TITLE
A way to avoid particular folders

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#183]
If its possible can we have a small feature of avoiding the selected folders from searching for cards?
Since, many people (and me) prefer making raw notes and then move them to our "main" folders when its kind of perfect.

I was hoping a simple option in the drop down menu of the folder deck menu itself wherewe can have an extra option basically to not include in searches.

**Comment by yo-goto** [comment]
This is so important feature for me. Specific custom syntax like Highlight-cloze style is really great, but not all of the things I highlight are all of what I want to turn into Anki flashcards . 

Besides, this may specific for me, my vault has Hugo and Zenn repository (for publisher cli) which have node modules and many unrelated stuff for Anki and knowledge base itself. it makes Folder Table so long and it takes long time to scan because Obsidian_to_Anki has only the ability to scan whole vault at the present. 

So, please consider adding these features in the future.
- command to scan just one file
- ignore scanning specific folder 
- ignore specific folders in Folder Table

**Comment by hrmck** [comment]
Similar situation here but with templates.
I have created templates like the below and put them into the "templates" folder.
![image](https://user-images.githubusercontent.com/16561876/113416868-27487100-93fd-11eb-9568-bad3b24abc8d.png)
I'm also using the templates plugin so I can create new card notes very quickly.
However, I don't want the templates to be added to Anki.

**Comment by yuanyowwu** [comment]
Using Regex for Basic Notes. Unfortunately, it's reading all my files. Would also like to have an option to specify which folders to be read in.

**Comment by dummifiedme** [comment]
> 
> 
> Using Regex for Basic Notes. Unfortunately, it's reading all my files. Would also like to have an option to specify which folders to be read in.
> 
> My workaround is to create a new vault and have that vault use the plugin.

I can feel the pain. 
I am having similar issues. But too bad the developer won't respond, I think he had exams.

**Comment by bathrobe** [comment]
please dr dev send help, the anki scan keeps crashing my vault for same reason!

**Comment by datavistics** [comment]
Any updates?

**Comment by dummifiedme** [comment]
Nothing. I switched over to Spaced Repetition plugin for in-obsidian
reviews.

**Comment by hektormisplon** [comment]
#289 is an open PR solving a similar issue.

**Comment by lsolesen** [comment]
@Pseudonium Any chance that you are going to implement this any time soon?

**Comment by sfelix1** [comment]
This would be of immense value!
