### ISSUE TITLE
This could take a few minutes lasts forever

### ISSUE THREAD

**Issue by slabzzz** [Pseudonium/Obsidian_to_Anki#348]
![image](https://user-images.githubusercontent.com/100169858/171352581-7844459b-bf1f-49ad-845a-666f1635a048.png)

I have a hunch that this is because I'm syncing with git for 2 devices, both using obsidian to anki. I'm currently using excalidraw, obsidian git, system dark mode, and obsidian to anki.

**Comment by slabzzz** [comment]
Ah nevermind it works. Just had to wait a while!

**Comment by niposch** [comment]
I have added a feature on my own branch of this project to address the issue this plugin has with excalidraw.
Having a few excalidraw files can take quite a lot of time to scan. (they are scanned because these files end with .md)
https://github.com/niposch/Obsidian_to_Anki/releases/tag/3.5.0_prerelease1
I added a setting where files/paths can be excluded.
The setting should have the same syntax as a git ignore file and adding **/*. excalidraw.md should exclude all excalidraw files from scanning.
I explained it here: #300
