### ISSUE TITLE
Error while providing a Vault Name

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#95]
1. I tried with the Vault Name. (Name had a space)
2. I tried removing the space.
3. I tried with the whole path to the Vault folder.
4. I tried to put ' "   " ' outside the path.

All the above cases led to the error.
![image](https://user-images.githubusercontent.com/68785729/99384445-6a45f400-28f5-11eb-97e7-ca2a1b59b331.png)

Please help me out 👍 
I would love to have a link to my md note :)

**Comment by Pseudonium** [comment]
Hmm, what's the name of your vault and what does the config file look like? I'll see if I can reproduce this error.

**Comment by dummifiedme** [comment]
Vault name just has words with no spaces like `TheNotebook`. 
I simple don't know if I have to provide the absolute path to the vault or just a name or relative path from the script.

**Comment by Pseudonium** [comment]
Ah, I think I figured out the problem! It couldn't find the name of your vault in the path you were adding the cards from for some reason, which threw an error. I've fixed this with my latest commit.

Though, what does the path look like? Because this means you won't be able to add a URL to link back to the obsidian file...

**Comment by dummifiedme** [comment]
That’s what I am confused about.
The path should be absolute or relative to the script?
Right now ai have kept my script on desktop (lol) and the files are a bit deep in the secondary drive (D). I should keep the script around my vault? Will that solve the problem?
